#!/usr/bin/env bash

full_path=$(readlink -f $1)
base_name=$(basename $full_path)

# current script's path
my_path=$(dirname $(readlink -f $0))
# shared directory's (local) location
shared=$my_path/../data/shared
# the hadoop env file
hadoop_env=$my_path/../resources/hadoop.env


if [ -d "${full_path}" ] ; then
    echo "$full_path is a directory"
    echo "Launching temporary container...\n\n"
    # we need to launch a temporary container that has this directory mounted
    # as a volume and call hdfs put from this container
    cf=/shared/$base_name
    docker run -it --rm\
       --env-file=$hadoop_env\
       --net host \
       --volume $full_path:$cf\
       cmantas/hadoop_base \
       hdfs dfs -Ddfs.replication=1 -put $cf $2

else
    if [ -f "${full_path}" ]; then
        echo "${full_path} is a file";
        echo 'Making temporary link'
        # hard link file
        ln $full_path $shared/$base_name
        # put to hdfs
        docker exec -it  datanode hdfs dfs -Ddfs.replication=1 -put /shared/$base_name $2
        # remove hard link
        rm $shared/$base_name
    else
        echo "${full_path} is not valid";
        exit 1
    fi
fi
